server:
  port: 3550

spring:
  config:
    import: optional:file:/etc/opengiraffe-java/config.yaml
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
