server:
  port: 3550

spring:
  config:
    import: optional:file:/etc/opengiraffe-java/config.yaml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
