package com.tddforge.service;

import com.tddforge.config.ModelConfigSnapshot;
import com.tddforge.config.ModelSpec;
import com.tddforge.config.OpencodeConfig;
import com.tddforge.config.RuntimeModelConfig;
import com.tddforge.web.dto.ModelConfigResponse;
import com.tddforge.web.dto.ModelConfigUpdateRequest;
import com.tddforge.web.dto.ModelSpecDto;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

@Service
public class ModelConfigService {

    private static final Logger log = LoggerFactory.getLogger(ModelConfigService.class);

    private static final String DEFAULT_CONFIG_DIR = System.getProperty("user.home") + "/.config/tddforge";
    private static final String MODEL_CONFIG_FILE = "model-config.yaml";

    private final RuntimeModelConfig runtimeModelConfig;
    private final OpencodeConfig opencodeConfig;
    private volatile String opencodeBinary = "opencode";
    private String configDir = DEFAULT_CONFIG_DIR;

    public ModelConfigService(RuntimeModelConfig runtimeModelConfig, OpencodeConfig opencodeConfig) {
        this.runtimeModelConfig = runtimeModelConfig;
        this.opencodeConfig = opencodeConfig;
    }

    @PostConstruct
    public void init() {
        loadPersistedConfig();
    }

    public void setOpencodeBinary(String opencodeBinary) {
        this.opencodeBinary = opencodeBinary;
    }

    public void setConfigDir(String configDir) {
        this.configDir = configDir;
    }

    public List<String> listAvailableModels() {
        try {
            ProcessBuilder pb = new ProcessBuilder(opencodeBinary, "models");
            pb.redirectErrorStream(true);
            Process process = pb.start();
            String output = new String(process.getInputStream().readAllBytes());
            boolean finished = process.waitFor(10, TimeUnit.SECONDS);
            if (!finished) {
                process.destroyForcibly();
                throw new RuntimeException("opencode models command timed out");
            }
            if (process.exitValue() != 0) {
                throw new RuntimeException("opencode models failed with exit code " + process.exitValue()
                        + ": " + output.trim());
            }
            return Arrays.stream(output.split("\n"))
                    .map(String::trim)
                    .filter(s -> !s.isEmpty())
                    .sorted()
                .collect(Collectors.toList());
        } catch (IOException e) {
            throw new RuntimeException("Failed to run opencode models: " + e.getMessage(), e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException("Interrupted while running opencode models", e);
        }
    }

    public ModelConfigResponse getCurrentConfig() {
        return toResponse(runtimeModelConfig.snapshot());
    }

    public void updateConfig(ModelConfigUpdateRequest request) {
        ModelConfigSnapshot prev = runtimeModelConfig.snapshot();
        ModelConfigSnapshot next = new ModelConfigSnapshot(
                request.getPlanner() != null ? toConfigSpec(request.getPlanner()) : prev.planner(),
                request.getTestWriter() != null ? toConfigSpec(request.getTestWriter()) : prev.testWriter(),
                request.getTestReviewer() != null ? toConfigSpec(request.getTestReviewer()) : prev.testReviewer(),
                request.getCoderDefault() != null ? toConfigSpec(request.getCoderDefault()) : prev.coderDefault(),
                request.getCoderByComplexity() != null ? buildComplexityMap(request.getCoderByComplexity()) : prev.coderByComplexity(),
                request.getReviewers() != null ? buildReviewerList(request.getReviewers()) : prev.reviewers()
        );
        runtimeModelConfig.replaceAll(next);
        persistConfig();
        log.info("Model configuration updated and persisted");
    }

    private void persistConfig() {
        try {
            Path dir = Path.of(configDir);
            Files.createDirectories(dir);
            Path configFile = dir.resolve(MODEL_CONFIG_FILE);

            ModelConfigSnapshot snap = runtimeModelConfig.snapshot();
            StringBuilder sb = new StringBuilder();
            sb.append("# Auto-generated by TDDForge - do not edit manually\n");
            sb.append("opencode:\n");

            appendModelSpec(sb, "planner", snap.planner());
            appendModelSpec(sb, "test_writer", snap.testWriter());
            appendModelSpec(sb, "test_reviewer", snap.testReviewer());
            appendModelSpec(sb, "coder_default", snap.coderDefault());

            if (!snap.coderByComplexity().isEmpty()) {
                sb.append("  coder_by_complexity:\n");
                snap.coderByComplexity().forEach((k, v) -> {
                    sb.append("    ").append(k).append(":\n");
                    sb.append("      model: ").append(quoteYaml(v.getModel())).append("\n");
                    if (v.getVariant() != null && !v.getVariant().isEmpty()) {
                        sb.append("      variant: ").append(quoteYaml(v.getVariant())).append("\n");
                    }
                    if (v.getAgent() != null && !v.getAgent().isEmpty()) {
                        sb.append("      agent: ").append(quoteYaml(v.getAgent())).append("\n");
                    }
                });
            }

            if (!snap.reviewers().isEmpty()) {
                sb.append("  reviewers:\n");
                snap.reviewers().forEach(v -> {
                    sb.append("    - model: ").append(quoteYaml(v.getModel())).append("\n");
                    if (v.getVariant() != null && !v.getVariant().isEmpty()) {
                        sb.append("      variant: ").append(quoteYaml(v.getVariant())).append("\n");
                    }
                    if (v.getAgent() != null && !v.getAgent().isEmpty()) {
                        sb.append("      agent: ").append(quoteYaml(v.getAgent())).append("\n");
                    }
                });
            }

            Files.writeString(configFile, sb.toString());
            log.debug("Persisted model config to {}", configFile);
        } catch (IOException e) {
            log.error("Failed to persist model config", e);
            throw new RuntimeException("Failed to persist model configuration: " + e.getMessage(), e);
        }
    }

    private void loadPersistedConfig() {
        Path configFile = Path.of(configDir, MODEL_CONFIG_FILE);
        if (!Files.exists(configFile)) {
            log.debug("No persisted model config found at {}", configFile);
            return;
        }
        try {
            String content = Files.readString(configFile);
            log.info("Loading persisted model config from {}", configFile);
            parseAndApplyYaml(content);
        } catch (IOException e) {
            log.warn("Failed to read persisted model config: {}", e.getMessage());
        }
    }

    private void parseAndApplyYaml(String content) {
        ModelSpec planner = null;
        ModelSpec testWriter = null;
        ModelSpec testReviewer = null;
        ModelSpec coderDefault = null;
        Map<String, ModelSpec> coderByComplexity = new LinkedHashMap<>();
        List<ModelSpec> reviewers = new ArrayList<>();

        String[] lines = content.split("\n");
        String currentSection = "";
        String currentSubSection = "";
        String currentComplexity = "";

        for (String line : lines) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;

            if (trimmed.equals("opencode:")) {
                currentSection = "opencode";
                continue;
            }
            if (!currentSection.equals("opencode")) continue;

            int indent = line.indexOf(trimmed);

            if (indent == 2 && trimmed.equals("planner:")) {
                currentSubSection = "planner"; currentComplexity = "";
            } else if (indent == 2 && trimmed.equals("test_writer:")) {
                currentSubSection = "test_writer"; currentComplexity = "";
            } else if (indent == 2 && trimmed.equals("test_reviewer:")) {
                currentSubSection = "test_reviewer"; currentComplexity = "";
            } else if (indent == 2 && trimmed.equals("coder_default:")) {
                currentSubSection = "coder_default"; currentComplexity = "";
            } else if (indent == 2 && trimmed.equals("coder_by_complexity:")) {
                currentSubSection = "coder_by_complexity"; currentComplexity = "";
            } else if (indent == 2 && trimmed.equals("reviewers:")) {
                currentSubSection = "reviewers"; currentComplexity = "";
            } else if (currentSubSection.equals("coder_by_complexity") && indent == 4 && trimmed.endsWith(":")) {
                currentComplexity = trimmed.substring(0, trimmed.length() - 1);
            } else if (indent >= 4 && trimmed.contains(":")) {
                String[] parts = trimmed.split(":", 2);
                String key = parts[0].trim();
                String value = parts.length > 1 ? unquoteYaml(parts[1].trim()) : "";

                if (currentSubSection.equals("reviewers") && indent == 4 && key.startsWith("- ")) {
                    String field = key.substring(2).trim();
                    ModelSpec spec = new ModelSpec();
                    applyField(spec, field, value, 6);
                    reviewers.add(spec);
                } else if (currentSubSection.equals("reviewers") && !reviewers.isEmpty()) {
                    ModelSpec last = reviewers.get(reviewers.size() - 1);
                    applyField(last, key, value, indent);
                } else if (currentSubSection.equals("coder_by_complexity") && !currentComplexity.isEmpty()) {
                    ModelSpec existing = coderByComplexity
                            .computeIfAbsent(currentComplexity, k -> new ModelSpec());
                    applyField(existing, key, value, indent);
                } else if (!currentSubSection.isEmpty() && !currentSubSection.equals("coder_by_complexity")
                        && !currentSubSection.equals("reviewers")) {
                    switch (currentSubSection) {
                        case "planner" -> { if (planner == null) planner = new ModelSpec(); applyField(planner, key, value, indent); }
                        case "test_writer" -> { if (testWriter == null) testWriter = new ModelSpec(); applyField(testWriter, key, value, indent); }
                        case "test_reviewer" -> { if (testReviewer == null) testReviewer = new ModelSpec(); applyField(testReviewer, key, value, indent); }
                        case "coder_default" -> { if (coderDefault == null) coderDefault = new ModelSpec(); applyField(coderDefault, key, value, indent); }
                    }
                }
            }
        }

        if (planner != null || testWriter != null || testReviewer != null || coderDefault != null
                || !coderByComplexity.isEmpty() || !reviewers.isEmpty()) {
            ModelConfigSnapshot prev = runtimeModelConfig.snapshot();
            ModelConfigSnapshot next = new ModelConfigSnapshot(
                    planner != null ? planner : prev.planner(),
                    testWriter != null ? testWriter : prev.testWriter(),
                    testReviewer != null ? testReviewer : prev.testReviewer(),
                    coderDefault != null ? coderDefault : prev.coderDefault(),
                    !coderByComplexity.isEmpty() ? coderByComplexity : prev.coderByComplexity(),
                    !reviewers.isEmpty() ? reviewers : prev.reviewers()
            );
            runtimeModelConfig.replaceAll(next);
        }
    }

    private void applyField(ModelSpec spec, String key, String value, int indent) {
        if (spec == null) return;
        switch (key) {
            case "model" -> spec.setModel(value);
            case "variant" -> spec.setVariant(value);
            case "agent" -> spec.setAgent(value);
        }
    }

    private void appendModelSpec(StringBuilder sb, String name, ModelSpec spec) {
        if (spec == null) return;
        sb.append("  ").append(name).append(":\n");
        sb.append("    model: ").append(quoteYaml(spec.getModel())).append("\n");
        if (spec.getVariant() != null && !spec.getVariant().isEmpty()) {
            sb.append("    variant: ").append(quoteYaml(spec.getVariant())).append("\n");
        }
        if (spec.getAgent() != null && !spec.getAgent().isEmpty()) {
            sb.append("    agent: ").append(quoteYaml(spec.getAgent())).append("\n");
        }
    }

    private static String quoteYaml(String value) {
        if (value == null) return "\"\"";
        if (value.contains(":") || value.contains("#") || value.contains("\"") || value.contains("'")) {
            return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
        }
        return value;
    }

    private static String unquoteYaml(String value) {
        if (value.length() >= 2 && value.startsWith("\"") && value.endsWith("\"")) {
            return value.substring(1, value.length() - 1)
                    .replace("\\\"", "\"")
                    .replace("\\\\", "\\");
        }
        if (value.equals("\"\"") || value.equals("''")) return "";
        return value;
    }

    private ModelConfigResponse toResponse(ModelConfigSnapshot snap) {
        return new ModelConfigResponse(
                toDto(snap.planner()),
                toDto(snap.testWriter()),
                toDto(snap.testReviewer()),
                toDto(snap.coderDefault()),
                toDtoMap(snap.coderByComplexity()),
                toDtoList(snap.reviewers())
        );
    }

    private ModelSpecDto toDto(ModelSpec spec) {
        if (spec == null) return null;
        return new ModelSpecDto(spec.getModel(), spec.getVariant(), spec.getAgent());
    }

    private Map<String, ModelSpecDto> toDtoMap(Map<String, ModelSpec> map) {
        if (map == null || map.isEmpty()) return null;
        Map<String, ModelSpecDto> result = new LinkedHashMap<>();
        map.forEach((k, v) -> result.put(k, toDto(v)));
        return result;
    }

    private List<ModelSpecDto> toDtoList(List<ModelSpec> list) {
        if (list == null || list.isEmpty()) return null;
        return list.stream().map(this::toDto).toList();
    }

    private ModelSpec toConfigSpec(ModelSpecDto dto) {
        if (dto == null) return null;
        ModelSpec spec = new ModelSpec();
        spec.setModel(dto.getModel());
        spec.setVariant(dto.getVariant() != null ? dto.getVariant() : "");
        spec.setAgent(dto.getAgent() != null ? dto.getAgent() : "");
        return spec;
    }

    private Map<String, ModelSpec> buildComplexityMap(Map<String, ModelSpecDto> source) {
        Map<String, ModelSpec> result = new LinkedHashMap<>();
        source.forEach((k, v) -> result.put(k, toConfigSpec(v)));
        return result;
    }

    private List<ModelSpec> buildReviewerList(List<ModelSpecDto> source) {
        List<ModelSpec> result = new ArrayList<>();
        source.forEach(v -> result.add(toConfigSpec(v)));
        return result;
    }
}
